// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AuthInfoType.
const (
	AuthInfoTypeApiKey AuthInfoType = "api_key"
	AuthInfoTypeUser   AuthInfoType = "user"
)

// Defines values for DatabaseStatus.
const (
	DatabaseStatusConfiguring DatabaseStatus = "configuring"
	DatabaseStatusDeleted     DatabaseStatus = "deleted"
	DatabaseStatusDeleting    DatabaseStatus = "deleting"
	DatabaseStatusPaused      DatabaseStatus = "paused"
	DatabaseStatusPausing     DatabaseStatus = "pausing"
	DatabaseStatusQueued      DatabaseStatus = "queued"
	DatabaseStatusResuming    DatabaseStatus = "resuming"
	DatabaseStatusRunning     DatabaseStatus = "running"
	DatabaseStatusUnknown     DatabaseStatus = "unknown"
	DatabaseStatusUnstable    DatabaseStatus = "unstable"
	DatabaseStatusUpgrading   DatabaseStatus = "upgrading"
)

// Defines values for DatabaseSize.
const (
	DatabaseSizeN1x DatabaseSize = "1x"
	DatabaseSizeN2x DatabaseSize = "2x"
	DatabaseSizeN4x DatabaseSize = "4x"
	DatabaseSizeN8x DatabaseSize = "8x"
)

// Defines values for DatabaseType.
const (
	DatabaseTypeDedicated DatabaseType = "dedicated"
	DatabaseTypeStandard  DatabaseType = "standard"
)

// Defines values for InvoiceStatus.
const (
	InvoiceStatusDelinquent InvoiceStatus = "delinquent"
	InvoiceStatusIssued     InvoiceStatus = "issued"
	InvoiceStatusPaid       InvoiceStatus = "paid"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyCredentials defines model for ApiKeyCredentials.
type ApiKeyCredentials struct {
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	AccessKey string `json:"access_key"`
	ApiKey    string `json:"api_key"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	SecretKey string `json:"secret_key"`
}

// ApiKeyInfo defines model for ApiKeyInfo.
type ApiKeyInfo struct {
	SpaceId   string `json:"space_id"`
	SpaceName string `json:"space_name"`
	UserEmail string `json:"user_email"`
	UserId    string `json:"user_id"`
	UserName  string `json:"user_name"`
}

// AuthInfo defines model for AuthInfo.
type AuthInfo struct {
	ApiKey *ApiKeyInfo  `json:"api_key,omitempty"`
	Type   AuthInfoType `json:"type"`
	User   *UserInfo    `json:"user,omitempty"`
}

// AuthInfoType defines model for AuthInfo.Type.
type AuthInfoType string

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	Name string `json:"name"`
}

// CreateDatabaseRequest defines model for CreateDatabaseRequest.
type CreateDatabaseRequest struct {
	Name *string `json:"name,omitempty"`

	// ShareToken Share token from a database share. When provided, creates a fork from the shared snapshot into this space.
	ShareToken *string       `json:"share_token,omitempty"`
	Size       *DatabaseSize `json:"size,omitempty"`
	Type       *DatabaseType `json:"type,omitempty"`
}

// CreateSpaceRequest defines model for CreateSpaceRequest.
type CreateSpaceRequest struct {
	Name string `json:"name"`
}

// Database defines model for Database.
type Database struct {
	Host       string         `json:"host"`
	Id         string         `json:"id"`
	Name       string         `json:"name"`
	Password   *string        `json:"password"`
	Port       int            `json:"port"`
	Size       *DatabaseSize  `json:"size,omitempty"`
	Status     DatabaseStatus `json:"status"`
	StorageMib *int           `json:"storage_mib"`
	Type       DatabaseType   `json:"type"`
}

// DatabaseStatus defines model for Database.Status.
type DatabaseStatus string

// DatabaseShare defines model for DatabaseShare.
type DatabaseShare struct {
	CreatedAt    time.Time  `json:"created_at"`
	DatabaseId   string     `json:"database_id"`
	DatabaseName string     `json:"database_name"`
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	Id           string     `json:"id"`
	RevokedAt    *time.Time `json:"revoked_at,omitempty"`
	ShareToken   string     `json:"share_token"`
}

// DatabaseSize defines model for DatabaseSize.
type DatabaseSize string

// DatabaseType defines model for DatabaseType.
type DatabaseType string

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// FeedbackRequest defines model for FeedbackRequest.
type FeedbackRequest struct {
	Message string `json:"message"`
	Os      string `json:"os"`
	Source  string `json:"source"`
	Version string `json:"version"`
}

// ForkDatabaseRequest defines model for ForkDatabaseRequest.
type ForkDatabaseRequest struct {
	Name *string       `json:"name,omitempty"`
	Size *DatabaseSize `json:"size,omitempty"`
	Type *DatabaseType `json:"type,omitempty"`
}

// IdentifyRequest defines model for IdentifyRequest.
type IdentifyRequest struct {
	Properties map[string]interface{} `json:"properties"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	// Id Opaque invoice ID used to look up invoice details.
	Id          string    `json:"id"`
	InvoiceDate time.Time `json:"invoice_date"`

	// InvoiceNumber Human-readable invoice number (e.g. "INV-12345").
	InvoiceNumber string `json:"invoice_number"`

	// Status Invoice status:
	// - `paid` — invoice has been paid.
	// - `issued` — invoice has been issued and is within its net-terms payment window (not yet paid, not yet delinquent).
	// - `delinquent` — payment has failed and the invoice needs to be resolved by the user.
	Status InvoiceStatus `json:"status"`

	// Total Invoice total.
	Total float64 `json:"total"`
}

// InvoiceStatus Invoice status:
// - `paid` — invoice has been paid.
// - `issued` — invoice has been issued and is within its net-terms payment window (not yet paid, not yet delinquent).
// - `delinquent` — payment has failed and the invoice needs to be resolved by the user.
type InvoiceStatus string

// InvoiceDetail defines model for InvoiceDetail.
type InvoiceDetail struct {
	LineItems []InvoiceLineItem `json:"line_items"`
}

// InvoiceLineItem defines model for InvoiceLineItem.
type InvoiceLineItem struct {
	// DatabaseId Ghost database ID this line item is attributed to, if any.
	DatabaseId *string `json:"database_id,omitempty"`

	// DetailedSpec Additional spec details (e.g. tier, size).
	DetailedSpec *string `json:"detailed_spec,omitempty"`

	// LineTotal Line total.
	LineTotal float64 `json:"line_total"`

	// ProductType Product category (e.g. storage, compute).
	ProductType string  `json:"product_type"`
	Quantity    float64 `json:"quantity"`

	// UnitPrice Unit price.
	UnitPrice float64 `json:"unit_price"`
}

// InvoicesResponse defines model for InvoicesResponse.
type InvoicesResponse struct {
	Invoices []Invoice `json:"invoices"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// LogsResponse defines model for LogsResponse.
type LogsResponse struct {
	Logs []string `json:"logs"`
}

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod struct {
	Brand           string `json:"brand"`
	ExpMonth        int    `json:"exp_month"`
	ExpYear         int    `json:"exp_year"`
	Id              string `json:"id"`
	Last4           string `json:"last4"`
	PendingDeletion bool   `json:"pending_deletion"`
	Primary         bool   `json:"primary"`
}

// PaymentMethodsResponse defines model for PaymentMethodsResponse.
type PaymentMethodsResponse struct {
	PaymentMethods []PaymentMethod `json:"payment_methods"`
}

// PaymentSetupResponse defines model for PaymentSetupResponse.
type PaymentSetupResponse struct {
	ClientSecret string `json:"client_secret"`
	PaymentUrl   string `json:"payment_url"`
}

// RenameDatabaseRequest defines model for RenameDatabaseRequest.
type RenameDatabaseRequest struct {
	Name string `json:"name"`
}

// ShareDatabaseRequest defines model for ShareDatabaseRequest.
type ShareDatabaseRequest struct {
	// ExpiresAt Timestamp after which the share expires. If omitted, the share does not expire.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// Space defines model for Space.
type Space struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// SpaceStatus defines model for SpaceStatus.
type SpaceStatus struct {
	BillingPeriodEnd    *time.Time `json:"billing_period_end,omitempty"`
	BillingPeriodStart  *time.Time `json:"billing_period_start,omitempty"`
	ComputeLimitMinutes int64      `json:"compute_limit_minutes"`
	ComputeMinutes      int64      `json:"compute_minutes"`

	// CostToDate Net cost accrued so far this billing cycle.
	CostToDate *float64 `json:"cost_to_date,omitempty"`

	// EstimatedTotalCost Projected net total for the current billing cycle based on usage to date.
	EstimatedTotalCost *float64 `json:"estimated_total_cost,omitempty"`
	StorageLimitMib    int64    `json:"storage_limit_mib"`
	StorageMib         int64    `json:"storage_mib"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// TrackRequest defines model for TrackRequest.
type TrackRequest struct {
	Event      string                  `json:"event"`
	Properties *map[string]interface{} `json:"properties,omitempty"`
}

// UpdatePasswordRequest defines model for UpdatePasswordRequest.
type UpdatePasswordRequest struct {
	Password string `json:"password"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email string `json:"email"`
	Id    string `json:"id"`
	Name  string `json:"name"`
}

// ApiKeyPrefix defines model for ApiKeyPrefix.
type ApiKeyPrefix = string

// DatabaseRef defines model for DatabaseRef.
type DatabaseRef = string

// PaymentId defines model for PaymentId.
type PaymentId = string

// SpaceId defines model for SpaceId.
type SpaceId = string

// DatabaseLogsParams defines parameters for DatabaseLogs.
type DatabaseLogsParams struct {
	Page  *int       `form:"page,omitempty" json:"page,omitempty"`
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`
}

// AnalyticsIdentifyJSONRequestBody defines body for AnalyticsIdentify for application/json ContentType.
type AnalyticsIdentifyJSONRequestBody = IdentifyRequest

// AnalyticsTrackJSONRequestBody defines body for AnalyticsTrack for application/json ContentType.
type AnalyticsTrackJSONRequestBody = TrackRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// SubmitFeedbackJSONRequestBody defines body for SubmitFeedback for application/json ContentType.
type SubmitFeedbackJSONRequestBody = FeedbackRequest

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = CreateDatabaseRequest

// ForkDatabaseJSONRequestBody defines body for ForkDatabase for application/json ContentType.
type ForkDatabaseJSONRequestBody = ForkDatabaseRequest

// UpdatePasswordJSONRequestBody defines body for UpdatePassword for application/json ContentType.
type UpdatePasswordJSONRequestBody = UpdatePasswordRequest

// RenameDatabaseJSONRequestBody defines body for RenameDatabase for application/json ContentType.
type RenameDatabaseJSONRequestBody = RenameDatabaseRequest

// ShareDatabaseJSONRequestBody defines body for ShareDatabase for application/json ContentType.
type ShareDatabaseJSONRequestBody = ShareDatabaseRequest
